"""empty message

Revision ID: 10e96b8c233e
Revises: 7a094188511f
Create Date: 2020-08-29 15:34:29.262832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10e96b8c233e'
down_revision = '7a094188511f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_user', sa.Column('email', sa.String(length=128), nullable=True))
    op.drop_index('mobile', table_name='info_user')
    op.create_unique_constraint(None, 'info_user', ['email'])
    op.drop_column('info_user', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_user', sa.Column('mobile', mysql.VARCHAR(length=11), nullable=False))
    op.drop_constraint(None, 'info_user', type_='unique')
    op.create_index('mobile', 'info_user', ['mobile'], unique=True)
    op.drop_column('info_user', 'email')
    # ### end Alembic commands ###
