"""empty message

Revision ID: 201883ccd1d1
Revises: 10e96b8c233e
Create Date: 2020-08-29 17:56:17.795629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201883ccd1d1'
down_revision = '10e96b8c233e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_news', sa.Column('is_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_news', 'is_delete')
    # ### end Alembic commands ###
