"""empty message

Revision ID: 273628604c5b
Revises: 201883ccd1d1
Create Date: 2020-08-29 18:47:03.792228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273628604c5b'
down_revision = '201883ccd1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_news', sa.Column('video', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_news', 'video')
    # ### end Alembic commands ###
