"""empty message

Revision ID: 99621a21afa0
Revises: f53113db4cdf
Create Date: 2020-08-29 20:56:15.845933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99621a21afa0'
down_revision = 'f53113db4cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_news', sa.Column('category_name', sa.String(length=256), nullable=True))
    op.drop_column('info_news', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_news', sa.Column('category', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('info_news', 'category_name')
    # ### end Alembic commands ###
