"""empty message

Revision ID: f53113db4cdf
Revises: 273628604c5b
Create Date: 2020-08-29 18:49:47.192374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53113db4cdf'
down_revision = '273628604c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_news', sa.Column('category', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_news', 'category')
    # ### end Alembic commands ###
